-- QUESTION 1

-- Question a
-- Write a query to calculate the total salary budget for each department
SELECT product_id, product_name, category,
SUM(price) OVER(PARTITION BY category) AS category_total_price
FROM products;
-- OVER(PARTITION) clause allows to perform a calculation across a set of rows without collapsing them into a single row like GROUP BY would


-- Question b
-- Write a query to find the dates and IDs of all transactions that have a total amount higher than the average amount of all transaction combined
SELECT transaction_id, transaction_date, total_amount
FROM transactions
WHERE total_amount > (SELECT AVG(total_amount) FROM transactions);
-- WHERE clause uses a subquery to calculate a single value first.
-- This value is then used as benchmark to filter the main transaction list


-- Question c
-- Write a query to list every item sold in the transaction_items table along with its corresponding product name
SELECT ti.transaction_id, p.product_name, p.stock_quantity
FROM transaction_items ti
JOIN products p ON ti.product_id = p.product_id;
-- Using JOIN combines rows from TRANSACTION_ITEMS and PRODUCTS only where there is matching PRODUCT_ID in both tables


-- Question d
-- Write a query to categorize customers based on their location
SELECT first_name, last_name, city,
	CASE
	WHEN city = 'San Diego' THEN 'Local'
	WHEN city = 'San Antonio' THEN 'Local'
	WHEN city = 'Chicago' THEN 'Coastal'
	WHEN city = 'Boston' THEN 'Coastal'
	WHEN city = 'Austin' THEN 'Central'
	WHEN city = 'Dallas' THEN 'Central'
	ELSE 'Other'
	END AS region_category
FROM customers;
-- The CASE structure acts like an IF-THEN-ELSE logic.
-- It evaluates the CITY columns row-by-row and assigns a text label based on the first condition that returns true


-- Question e
-- Write a query to calculate a running total of stock_quantity across the products table
SELECT product_id, product_name, stock_quantity,
SUM(stock_quantity) OVER(ORDER BY product_id) AS running_stock_count
FROM products;
-- OVER(ORDER BY PRODUCT_ID) clause create the running effect
-- Using ORDER BY but not PARTITON, SQL adds the current row's value to the sum of all previous rows


-- QUESTION 2

-- Question a
-- Write a query to calculate the average transaction amount spent by customers partitioned by the customer city
SELECT t.transaction_id, c.city, t.total_amount,
AVG(t.total_amount) OVER(PARTITION BY c.city) AS city_avg_spend
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id;
-- This operation combines a JOIN to get the CITY name with an AVG() OVER()
-- to calculate the regional averages.



-- Question b
-- Write a query to find the names of all products that have never been sold
SELECT product_id, product_name
FROM products
WHERE product_id NOT IN(
	SELECT product_id
	FROM transaction_items
)
ORDER BY product_id;
-- The NOT IN operator compares the PRODUCT_ID against a list generated by the subquery.
-- This is the standard way to find missing records between to related tables




-- Question c
-- Write a query to list all transactions including the email of the customer who made them
SELECT t.transaction_id, t.transaction_date, c.email
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id;
-- A JOIN used to pull related attributes from a separate table using the CUSTOMER_ID foreign key



-- Question d
-- Write a query to categorize products based on their price
SELECT product_name, price,
	CASE
		WHEN price > 10.00 THEN 'Premium'
		WHEN price BETWEEN 5.00 AND 10.00 THEN 'Mid-Range'
		WHEN price < 5.00 THEN 'Budget'
		ELSE 'Unpriced'
	END AS price_tier
FROM products;
-- This uses BETWEEN and comparison operators (>,<) to bucket numerical data into categorical



-- Question e
-- Write a query to find the maximum stock quantity available within each product category
SELECT category,
MIN(stock_quantity) AS minimum_stock,
MAX(stock_quantity) AS maximum_stock
FROM products
GROUP BY category;
-- GROUP BY collapse all individual products into a single row per category
-- MIN(), MAX() functions find the extreme values within those collapsed groups
