-- Question a
-- Write a query to calculate the total revenue generated by each product across all transactions
SELECT DISTINCT -- Using DISTINCT to ensure each product only see once instead of repeated every time it was sold
p.product_id, p.product_name,
SUM(ti.quantity * ti.price) -- To calculates the revenue amount sould * price at time of sale
OVER(PARTITION BY p.product_id) AS product_revenue -- To group the calculations by product. It sums up all the revenue specifically for that ID and then resets for the next one
FROM products p
JOIN transaction_items ti ON p.product_id = ti.product_id;


-- Question b
-- Write a query to identify all transactions where the total_amount is lower than the overall average transaction amount
SELECT transaction_id, transaction_date, total_amount
FROM transactions
WHERE total_amount < (SELECT AVG(total_amount) FROM transactions); -- The subquery will run first
																   -- It calculate the average of every TOTAL_AMOUNT in the entire table
-- Using a scalar subquery to identify transactions that fall below average
-- Subquery calculates one single number which the main query then uses to filter the results


-- Questions c
-- Write a query to list every item sold, including the customer's name and the date it was bought 
SELECT c.first_name, c.last_name, t.transaction_date, ti.product_id
FROM customers c
JOIN transactions t ON c.customer_id = t.customer_id
JOIN transaction_items ti ON t.transaction_id = ti.transaction_id;
-- Need to use link three separate tables using a chain of JOINS to list every item sold with customer details
-- Starting with the customer, find their transaction, and then look inside the transactions to see the specific items


-- Questions d
-- Categorize your customers based on the number of transactions they have made
-- Use CASE Statement
-- 'Frequent' for customers with more than 3 transactions
-- 'Regular' for customers with 1 to 3 transactions
-- 'New' for customers with 0 transactions
SELECT c.customer_id, c.last_name,
	CASE
		WHEN COUNT(t.transaction_id) > 3 THEN 'Frequent'
		WHEN COUNT(t.transaction_id) BETWEEN 1 AND 3 THEN 'Regular'
		ELSE 'New'
	END AS loyalty_tier
FROM customers c
LEFT JOIN transactions t ON c.customer_id = t.customer_id -- A standard JOIN would skip customers with 0 transaction. LEFT JOIN keeps every customer in the list
GROUP BY c.customer_id, c.last_name; -- Since using an aggregate function (COUNT), it must group by non-calculated columns to get one row per person
-- To categorize customers based on their activity, it first need to count how many transactions each person has.
-- This requires a LEFT JOIN (to include customers with 0 transactions) and a CASE statement to assign the labels


-- Question e
-- Calculate the running total of stock quantities within each product category
SELECT category, product_name,
SUM(stock_quantity) OVER(PARTITION BY category ORDER BY product_name) AS category_running_stock
FROM products;
-- To calculate a running total within specific groups,
-- need to combine PARTITION BY (to group by category) and ORDER BY (to create the accumulation) within window function


-- Question f
-- Find products that are more expensive than the average price within their specifc category
WITH category_averages AS (
	SELECT product_name, category, price,
	AVG(price) OVER(PARTITION BY category) AS avg_category_price
	FROM products
)
SELECT product_name, category, price, avg_category_price
FROM category_averages
WHERE price > avg_category_price
ORDER BY price DESC;
-- Using a Common Table Expression (CTE) because, SQL does not allow to use a window function directly in a WHERE clause
-- Need to calculate the averages in a temporary result set (the CET) first
-- and then filter that result set